// MILO — Program Builder API
// Takes a client snapshot + block intent, returns a 4-week training
// program draft generated by Claude. Used by /build.html.
//
// Required env var: ANTHROPIC_API_KEY

import Anthropic from '@anthropic-ai/sdk';

export const config = { api: { bodyParser: { sizeLimit: '4mb' } } };

const SYSTEM_PROMPT = `You are MILO, a senior strength & conditioning coach working with Marin Lazic at Otion Performance. You write training programs for his individual clients (executives, high-performers, sport-specific athletes).

You will be given a structured snapshot of one athlete:
- Demographics + body weight + active programs
- 12-week training history (weekly bucketed: sessions, duration, avg RPE, sRPE training load)
- ACWR (acute:chronic workload ratio) + zone
- Movement profile (push/pull ratio, planes of motion %, body region split)
- Strength progression per exercise (e1RM time series from athlete-logged sets)
- Block intent (the coach's target: strength / hypertrophy / power / deload / GPP / off-season / pre-season / etc.)
- Duration in weeks

Output a 4-week program block as a STRUCTURED JSON object with this exact shape:

{
  "blockName": "concise name, e.g. 'May Power & Carry Block'",
  "phase": "the intent (e.g. 'Hypertrophy')",
  "rationale": "2-3 sentence paragraph: why this block now, given the athlete's current state. Reference actual numbers from the data.",
  "sessionsPerWeek": 3,
  "estimatedMinutesPerSession": 50,
  "weeks": [
    {
      "weekNumber": 1,
      "theme": "build / intro / load / deload (short phrase)",
      "sessions": [
        {
          "name": "Hinge + Posterior Shoulder",
          "estimatedMinutes": 50,
          "blocks": [
            {
              "name": "Mobility Prep",
              "minutes": 5,
              "exercises": [
                { "name": "Cat-Cow", "sets": 1, "reps": "10 each", "loadCue": "BW" }
              ]
            },
            {
              "name": "Primary Hinge",
              "exercises": [
                { "name": "Trap Bar Deadlift", "sets": 4, "reps": 5, "loadCue": "~80% e1RM (work up to RPE 7)", "rest": "120s", "note": "He just hit 159kg e1RM. Conservative top set." }
              ]
            }
          ]
        }
      ]
    }
  ],
  "notesForCoach": "Bullet list of things Marin should watch for during this block (e.g. recovery, technique cues, week-to-week adjustments)."
}

DESIGN RULES — STRICT:

1. **Match Marin's coaching style.** Look at the workouts the athlete has done recently (names like "Hinge, Carry, Core" / "Vertical Pull + Lower Unilateral" / "Pull, Posterior Shoulder, Hip"). Use this same naming pattern for sessions. He does compound multi-pattern sessions, not bodybuilder splits.

2. **Use exercises the athlete has actually done before** where possible — pull names from their strength progression and recent workouts. If you need to introduce a new exercise, make it adjacent (same pattern family) and explain why in the exercise note.

3. **Address the gaps the data shows.** If push:pull is 8:11 (pull-heavy), add a push session. If frontal/transverse plane is 0%, add lateral or rotation work. If a body region hasn't been trained, include it.

4. **Respect the ACWR.** If they're in the danger zone (>1.5), build in a deload week. If they're undertrained (<0.8), ramp gradually. If sweet spot, keep building.

5. **Use their actual strength numbers.** Reference their e1RM where available. Prescribe loads as % of e1RM rather than absolute kg unless you have a strong reason. Note kg estimates in parentheses where useful.

6. **Be specific.** No "3-5 sets". Pick 3 or pick 5. No "moderate weight". Say "75% e1RM" or "RPE 7".

7. **Reasonable session count.** 3 sessions/week is the default for most H&P clients. 4 if intent is high-volume. 2 for deload weeks.

8. **Include warm-up and cool-down/finisher blocks** in each session. Marin's sessions always include Mobility Prep at start.

9. **Output ONLY valid JSON.** No prose before or after. No markdown code fences. Just the JSON object.`;

export default async function handler(req, res) {
  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST')    return res.status(405).json({ error: 'POST only' });

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return res.status(200).json({
      setupNeeded: true,
      message: 'Add ANTHROPIC_API_KEY to your Vercel environment variables to enable program generation. Get a key at console.anthropic.com → API Keys.',
    });
  }

  try {
    const { snapshot, blockIntent, durationWeeks, clientId, templateId, frequency, conditioningZone } = req.body || {};
    if (!snapshot) return res.status(400).json({ error: 'Missing snapshot' });

    // Load coaching principles + per-athlete notes + template library (best-effort)
    const [principles, allNotes, templatesFile] = await Promise.all([
      fetchJsonFile('coaching-principles.json'),
      fetchJsonFile('athlete-notes.json'),
      fetchJsonFile('program-templates.json'),
    ]);
    const athleteNotes = (allNotes && clientId) ? allNotes[clientId] : null;
    const chosenTemplate = (templateId && templatesFile?.templates) ? templatesFile.templates[templateId] : null;

    const contextSections = [];
    if (principles) {
      contextSections.push(`MARIN'S COACHING SYSTEM (his philosophy, exercise preferences, and rules — match these as if Marin wrote the program himself):
${JSON.stringify(stripMeta(principles), null, 2)}`);
    }
    if (athleteNotes && Object.values(athleteNotes).some(v => v && String(v).trim())) {
      contextSections.push(`ATHLETE-SPECIFIC CONSIDERATIONS (these override generic programming — work around injuries, respect equipment, honour the stated goals):
${JSON.stringify(athleteNotes, null, 2)}`);
    }
    if (chosenTemplate) {
      const freq = frequency || chosenTemplate.defaultFrequency || (chosenTemplate.sessions || []).length;
      // Build the actual cycling week (e.g. A-B-A for 3x/week from a 2-session template)
      const weekCycle = [];
      const uniqueCount = (chosenTemplate.sessions || []).length;
      for (let i = 0; i < freq; i++) weekCycle.push((chosenTemplate.sessions || [])[i % uniqueCount]?.name || `Day ${i+1}`);
      contextSections.push(`SCAFFOLD TEMPLATE (the coach has selected this blueprint — use it as the STRUCTURAL skeleton).

RULES — STRICT:
- The coach selected ${freq} sessions per week. The week's session order is: ${weekCycle.join(' → ')}.
- Build ${durationWeeks || 4} weeks at this frequency. Each week uses this same cycle.
- Keep the block ORDER, intensity levels, set/rep schemes, pair labels, and pattern distribution exactly as in the template.
- Mobility blocks (pattern: "mobility", with a category) are part of the session flow — render them with their own block name like "Hip Mobility" / "T-Spine Mobility" / "Ankle Mobility", and pick ONE exercise from the matching mobility_pools, varying across sessions and weeks.
- Conditioning blocks (pattern: "conditioning", with a zone): ${conditioningZone ? `OVERRIDE the template's zone — the coach explicitly selected zone ${conditioningZone}. Use it for all conditioning blocks this build.` : 'Use the zone specified in the template block.'}
- For each strength block, pick a specific exercise from the athlete's preferred_exercises pool that matches the pattern. Reference their actual e1RM if available.
- Set/rep ranges in the template (e.g. "1-2 x 15"): pick a specific number for each week within the range, varying across the block (e.g. week 1 = 1 set, week 2 = 1 set, week 3 = 2 sets, week 4 = deload).
- DAILY UNDULATING PERIODIZATION: if the template has an "undulating" object with "type": "daily" and a "dailyRotation" array, that template uses DUP. Each session in a week uses a DIFFERENT sets×reps scheme from the dailyRotation array — NOT each week. Apply scheme N to the Nth session of the week. At 3x/week with 3 schemes, each session in the week uses a different scheme; the same exercises repeat next week with the same rotation. At 2x/week, drop the last scheme. At 4x/week, repeat from scheme 1 for the 4th session. The exercise template (A/B) alternates separately and independently of the scheme rotation. Apply the dailyRotation's sets and reps ONLY to the strength superset blocks (pairs 1a/1b and 2a/2b); leave core, power, mobility, and finisher blocks at their template defaults.

TEMPLATE:
${JSON.stringify(chosenTemplate, null, 2)}`);
    }
    if (principles?.mobility_pools) {
      contextSections.push(`MOBILITY EXERCISE POOLS (use these when filling in a mobility block — pick 1 exercise from the matching category, vary across sessions for the same athlete):
${JSON.stringify(principles.mobility_pools, null, 2)}`);
    }
    if (principles?.session_balance_rules && chosenTemplate) {
      contextSections.push(`SESSION BALANCE RULES (apply alongside the template):
${JSON.stringify(stripDocs(principles.session_balance_rules), null, 2)}`);
    }
    if (!chosenTemplate && principles?.mobility_pools) {
      contextSections.push(`MOBILITY REQUIREMENT (free-form mode — no template was provided): include mobility blocks across each week so the athlete covers ankle, hip, and t-spine. Typical pattern: hip mobility mid-session in one workout, t-spine mid-session in another, ankle as cool-down. Pull exercises from the mobility_pools above.`);
    }

    const userContent = `BLOCK PARAMETERS
- Intent: ${blockIntent || 'general progression / strength + balance'}
- Duration: ${durationWeeks || 4} weeks

${contextSections.join('\n\n')}${contextSections.length ? '\n\n' : ''}ATHLETE SNAPSHOT (training data)
${JSON.stringify(snapshot, null, 2)}

Write the program now. Output ONLY the JSON object, no other text.`;

    const anthropic = new Anthropic({ apiKey });
    const msg = await anthropic.messages.create({
      model: 'claude-sonnet-4-5',
      max_tokens: 4096,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: userContent }],
    });

    const text = msg.content
      .filter(b => b.type === 'text')
      .map(b => b.text)
      .join('\n')
      .trim();

    // Try to parse JSON. Claude sometimes wraps in ```json ... ``` despite instructions.
    let program;
    try {
      let clean = text;
      if (clean.startsWith('```')) {
        clean = clean.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '');
      }
      program = JSON.parse(clean);
    } catch (e) {
      return res.status(500).json({
        error: 'Claude returned non-JSON',
        raw: text.slice(0, 2000),
      });
    }

    return res.status(200).json({
      program,
      model: msg.model,
      usage: msg.usage,
      generatedAt: new Date().toISOString(),
      contextUsed: {
        principles: !!principles,
        athleteNotes: !!athleteNotes && Object.values(athleteNotes || {}).some(v => v && String(v).trim()),
        template: chosenTemplate ? chosenTemplate.name : null,
      },
    });
  } catch (err) {
    console.error('Program generation error:', err);
    return res.status(500).json({
      error: 'Program generation failed',
      detail: err.message || String(err),
    });
  }
}

// Fetch a JSON file from the deployed site (sibling files in the same repo)
async function fetchJsonFile(filename) {
  try {
    const host = process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'https://milo-cyan.vercel.app';
    const r = await fetch(`${host}/${filename}`, { cache: 'no-store' });
    if (!r.ok) return null;
    return await r.json();
  } catch (e) { return null; }
}

function stripMeta(obj) {
  if (!obj || typeof obj !== 'object') return obj;
  const { _meta, ...rest } = obj;
  return JSON.parse(JSON.stringify(rest, (k, v) => k === '_docs' ? undefined : v));
}

function stripDocs(obj) {
  if (!obj || typeof obj !== 'object') return obj;
  return JSON.parse(JSON.stringify(obj, (k, v) => k === '_docs' ? undefined : v));
}
